"""Build data/raw/john6.greek.json and data/raw/lexicon.john6.json from STEPBible-Data.

Usage: python3 data/scripts/build_greek.py [Book] [chapter]   (defaults: Jhn 6)
"""
import json
import re
import sys
from collections import defaultdict, OrderedDict
from pathlib import Path

from greek_common import (iter_tagnt, load_pos_names, NT_OSIS, split_greek, split_strong_grammar, simple_strong,
                          transliterate, load_tegmc, human_parse, load_tbesg, clean_html,
                          in_na28, in_tr)

OUT = Path(__file__).resolve().parent.parent / "raw"
BOOK = sys.argv[1] if len(sys.argv) > 1 else "Jhn"
CHAPTER = int(sys.argv[2]) if len(sys.argv) > 2 else 6
FOCUS = range(47, 59)  # John 6:47-58: lemmas here get full NT reference lists
REFS_CAP = 1000        # skip ref lists for function words above this NT frequency

OSIS = NT_OSIS
pos_names = load_pos_names()
tegmc = load_tegmc()
tbesg = load_tbesg()


def fix_case(s):
    return s.replace("hebrew", "Hebrew").replace("aramaic", "Aramaic")


def lemma_parts(cell):
    """'ἔπω, ἐρῶ, εἶπον=to say' -> [('ἔπω, ἐρῶ, εἶπον','to say')]; handles ' + '."""
    out = []
    for p in cell.split(" + "):
        if "=" in p:
            l, g = p.split("=", 1)
            out.append((l.strip(), g.strip()))
        else:
            out.append((p.strip(), None))
    return out


# ---------------------------------------------------------------- pass 1: whole NT
nt_count = defaultdict(int)          # dStrong -> NA28 word count
nt_count_all = defaultdict(int)      # dStrong -> count in any edition
nt_refs = defaultdict(list)          # dStrong -> NA28 refs (ordered, unique)
chapter_words = []
for w in iter_tagnt():
    sg = split_strong_grammar(w["strongGrammar"])
    ref = f"{NT_OSIS[w['book']]}.{w['chapter']}.{w['verse']}"
    for d, _g in sg:
        nt_count_all[d] += 1
        if in_na28(w):
            nt_count[d] += 1
            lst = nt_refs[d]
            if not lst or lst[-1] != ref:
                lst.append(ref)
    if w["book"] == BOOK and w["chapter"] == CHAPTER:
        chapter_words.append(w)

# ---------------------------------------------------------------- pass 2: chapter words
words = []
verses = OrderedDict()
for w in chapter_words:
    greek, punct, step_tr, para = split_greek(w["greekCell"])
    sg = split_strong_grammar(w["strongGrammar"])
    lp = lemma_parts(w["lemmaGloss"])
    ref = f"{OSIS.get(BOOK, BOOK)}.{w['chapter']}.{w['verse']}"
    morph = " + ".join(g for _, g in sg)
    rec = OrderedDict([
        ("ref", ref),
        ("position", w["position"]),
        ("greek", greek),
        ("punctuation", punct or None),
        ("paragraphAfter", para),
        ("transliteration", transliterate(greek)),
        ("transliterationStep", step_tr),
        ("lemma", " + ".join(l for l, _ in lp)),
        ("lemmaTransliteration", " + ".join(transliterate(l.split(",")[-1].strip()) for l, _ in lp)),
        ("strong", " + ".join(simple_strong(d) for d, _ in sg)),
        ("dStrong", " + ".join(d for d, _ in sg)),
        ("morph", morph),
        ("parse", fix_case(human_parse(morph, tegmc))),
        ("englishGloss", re.sub(r"[,.;:·!?]+$", "", w["english"]).strip()),
        ("lexicalGloss", " + ".join(g for _, g in lp if g)),
        ("contextGloss", re.sub(r"[»|@].*$", "", w["subMeaning"]).lstrip(": ").strip() or None),
        ("spanishGloss", w["spanish"] or None),
        ("textType", w["type"]),
        ("editions", w["editions"].split("+") if w["editions"] else []),
        ("inNA28", in_na28(w)),
        ("inTR", in_tr(w)),
        ("meaningVariant", w["meaningVariants"] or None),
        ("variantNote", re.sub(r"<[^>]+>", "", w["variantNote"]).strip() or None),
    ])
    words.append(rec)
    v = verses.setdefault(str(w["verse"]), [])
    if rec["inNA28"]:
        v.append(greek + (punct or ""))

verse_text = OrderedDict((k, " ".join(v)) for k, v in verses.items())

SOURCE = OrderedDict([
    ("name", "STEPBible TAGNT (Translators Amalgamated Greek NT)"),
    ("url", "https://github.com/STEPBible/STEPBible-Data"),
    ("license", "CC BY 4.0"),
    ("attribution", "Data from STEP Bible (www.STEPBible.org), based on work at Tyndale House Cambridge. CC BY 4.0."),
    ("notes", [
        "English glosses: STEPBible, based on the Berean Study Bible (used by STEPBible with permission; BSB itself is public domain since 2023).",
        "Spanish glosses: from TAGNT, which takes them from the Open Greek New Testament / Marvel Bible project (Eliran Wong), CC BY-SA 4.0. Treat spanishGloss as CC BY-SA 4.0 (share-alike) and attribute OpenGNT.",
        "Morphology: Robinson-style codes (TAGNT, based on James Tauber's MorphGNT), expanded with STEPBible TEGMC (CC BY 4.0).",
        "Lemma/lexicalGloss: STEPBible TBESG (CC BY 4.0).",
        "transliteration: generated by Doctrina (SBL academic scheme; accents and iota subscript not marked). transliterationStep: STEPBible's own transliteration.",
        "Word list includes every word in NA27/28, TR, Byzantine, SBLGNT, Tyndale House GNT, WH and Tregelles. Use inNA28 for the modern critical text and inTR for the KJV text.",
        "Changes from source: Greek split from punctuation; morph codes expanded to English; sub-meaning trimmed of STEPBible cross-reference markup. No lexical data changed.",
    ]),
])

greek_out = OrderedDict([
    ("book", OSIS.get(BOOK, BOOK)), ("chapter", CHAPTER), ("source", SOURCE),
    ("verseCount", len(verses)), ("wordCount", len(words)),
    ("wordCountNA28", sum(1 for w in words if w["inNA28"])),
    ("versesNote", "verses = NA28 text assembled from words with inNA28=true (punctuation per THGNT as in TAGNT). TR/Byzantine readings that differ only by form are in each word's meaningVariant, so a TR text cannot be rebuilt from inTR words alone."),
    ("verses", verse_text), ("words", words),
])
(OUT / f"{OSIS.get(BOOK, BOOK).lower()}{CHAPTER}.greek.json").write_text(
    json.dumps(greek_out, ensure_ascii=False, indent=1), encoding="utf-8")

# ---------------------------------------------------------------- lexicon
focus_strongs = set()
lex_ids = OrderedDict()
for w in chapter_words:
    for d, _ in split_strong_grammar(w["strongGrammar"]):
        lex_ids.setdefault(d, None)
        if w["verse"] in FOCUS:
            focus_strongs.add(d)


def short_definition(html, gloss):
    """First substantive sense of the Abbott-Smith/TBESG entry, as plain text."""
    txt = clean_html(html)
    # drop leading headword line and LXX-equivalent bracket lines
    lines = [l for l in txt.split("\n") if l.strip()]
    keep = []
    for l in lines[1:] if len(lines) > 1 else lines:
        if l.startswith("[in LXX") or l.startswith("[in LXX"):
            continue
        keep.append(l)
    s = " ".join(keep).strip()
    s = re.sub(r"\s+", " ", s)
    if len(s) > 400:
        cut = s[:400]
        cut = cut[: max(cut.rfind(";"), cut.rfind("."), 200)]
        s = cut.rstrip(" ,;") + " ..."
    return s or gloss


lexicon = []
for d in lex_ids:
    e = tbesg.get(d) or tbesg.get(simple_strong(d))
    if not e:
        lexicon.append({"strong": simple_strong(d), "dStrong": d, "missing": True})
        continue
    rec = OrderedDict([
        ("strong", simple_strong(d)),
        ("dStrong", d),
        ("lemma", e["lemma"]),
        ("transliteration", transliterate(e["lemma"])),
        ("partOfSpeech", fix_case(pos_names.get(e["morph"], e["morph"]))),
        ("shortGloss", e["gloss"]),
        ("definition", short_definition(e["definitionHtml"], e["gloss"])),
        ("definitionFull", clean_html(e["definitionHtml"])),
        ("formOf", e["uStrong"] if "Form" in e["relation"] else None),
        ("definitionSource", "Abbott-Smith, Manual Greek Lexicon of the NT (1922, public domain) via STEPBible TBESG (CC BY 4.0)"
            if e["definitionHtml"].rstrip().endswith("(AS)") else "STEPBible TBESG (CC BY 4.0)"),
        ("occurrencesNT", nt_count.get(d, 0)),
        ("occurrencesNTAnyEdition", nt_count_all.get(d, 0)),
        ("versesNT", len(nt_refs.get(d, []))),
        ("inJohn6_47_58", d in focus_strongs),
    ])
    if d in focus_strongs:
        refs = nt_refs.get(d, [])
        rec["refs"] = refs if nt_count.get(d, 0) <= REFS_CAP else None
        if rec["refs"] is None:
            rec["refsNote"] = f"omitted: function word with more than {REFS_CAP} NT occurrences"
    lexicon.append(rec)

lex_out = OrderedDict([
    ("scope", f"Every distinct Strong's number (STEPBible disambiguated dStrong) in {OSIS.get(BOOK, BOOK)} {CHAPTER}"),
    ("source", OrderedDict([
        ("name", "STEPBible TBESG (Translators Brief lexicon of Extended Strongs for Greek)"),
        ("url", "https://github.com/STEPBible/STEPBible-Data/tree/master/Lexicons"),
        ("license", "CC BY 4.0"),
        ("attribution", "Lexicon from STEP Bible (www.STEPBible.org), based on Abbott-Smith's Manual Greek Lexicon of the New Testament (public domain); CC BY 4.0."),
    ])),
    ("countsMethod", "occurrencesNT = word tokens tagged with this dStrong in the NA28 text of STEPBible TAGNT; "
                     "occurrencesNTAnyEdition = tokens in any edition (NA27/28, TR, Byz, SBL, THGNT, WH, Treg); "
                     "refs = unique NA28 verse references (only for lemmas in John 6:47-58, and only when occurrencesNT <= 1000). "
                     "Counts are by STEPBible dStrong, so suppletive forms tagged separately (e.g. φαγεῖν G5315 vs ἐσθίω G2068) are counted separately."),
    ("count", len(lexicon)),
    ("entries", lexicon),
])
(OUT / f"lexicon.{OSIS.get(BOOK, BOOK).lower()}{CHAPTER}.json").write_text(
    json.dumps(lex_out, ensure_ascii=False, indent=1), encoding="utf-8")
print("words", len(words), "verses", len(verses), "lexicon", len(lexicon),
      "missing", sum(1 for x in lexicon if x.get("missing")))
